# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "laocnftisgmcjwylzgzz"

[functions]
[functions.create-checkout]
verify_jwt = true
[functions.create-connect-account]
verify_jwt = true
[functions.stripe-webhook]
verify_jwt = false
[functions.checkout-webhook]
verify_jwt = false
[functions.restart-connect-account]
verify_jwt = true